name: Terraform CI/CD

on:
  push:
    branches: 
      - '*'         
      - '*/*'       
      - '**'        
      - '!master'    

jobs:
  terraform-scan:
    runs-on: tfsec/tfsec

    steps:
      - uses: actions/checkout@v3
        path: ./intuitive-test

      - name: terraform-scan
        run: tfsec ./intuitive-test/terraform

  terraform:
    runs-on: hashicorp/terraform:1.4

    steps:
      - uses: actions/checkout@v3
        path: ./intuitive-test

      - name: terraform-init
        run: terraform init

      - name: terraform-validate
        run: terraform validate

      - name: terraform-plan
        run: terraform plan